import { StyleSheet } from 'react-native';
import { COLORS } from '../utils/constants';

export const commonStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.backgroundLight },
  containerCenter: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20, backgroundColor: COLORS.backgroundLight },
  centerContainer: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 20 },
  scrollContent: { padding: 20, paddingBottom: 100 },
  label: { fontWeight: '600', marginTop: 15, marginBottom: 5, color: COLORS.inkBlack, fontSize: 14, textTransform: 'uppercase', letterSpacing: 1 },
  bigTitle: { fontSize: 32, fontWeight: '800', marginBottom: 20, letterSpacing: -1, color: COLORS.inkBlack },
  headerTitle: { fontSize: 24, fontWeight: 'bold', marginBottom: 20, marginTop: 10, textAlign: 'center', color: COLORS.inkBlack },
  input: { width: '100%', padding: 16, backgroundColor: COLORS.cardWhite, borderRadius: 12, marginBottom: 15, fontSize: 16, borderWidth: 1, borderColor: COLORS.inputBorder, color: COLORS.inkBlack },
  primaryBtn: { width: '100%', padding: 16, backgroundColor: COLORS.darkTeal, borderRadius: 12, alignItems: 'center', marginTop: 10 },
  btnText: { color: COLORS.white, fontWeight: '700', fontSize: 16 },
  roleBtn: { width: '100%', padding: 22, borderRadius: 16, marginBottom: 20 },
  roleBtnText: { color: COLORS.white, fontSize: 18, fontWeight: '800', textAlign: 'center', letterSpacing: 1 },
  filterContainer: { 
    width: '100%', 
    alignItems: 'center', 
    marginTop: 20,
    marginBottom: 10, 
    zIndex: 100 
  },
  filterPill: { 
    flexDirection: 'row', 
    backgroundColor: COLORS.cardWhite, 
    paddingVertical: 12, 
    paddingHorizontal: 24, 
    borderRadius: 25, 
    alignItems: 'center', 
    gap: 8,
    shadowColor: COLORS.inkBlack, 
    shadowOffset: { width: 0, height: 5 }, 
    shadowOpacity: 0.2, 
    shadowRadius: 10, 
    elevation: 8,
    borderWidth: 1,
    borderColor: COLORS.inputBorder,
    alignSelf: 'center'
  },
  filterPillText: { fontWeight: '600', color: COLORS.inkBlack, fontSize: 13, letterSpacing: 0.5 },
  swiperFlexContainer: { 
    flex: 1, 
    justifyContent: 'center', 
    alignItems: 'center', 
    zIndex: 1, 
    marginTop: 15,
    marginBottom: 85 
  },
  card: { 
    height: 600,
    borderRadius: 24, 
    backgroundColor: COLORS.cardWhite, 
    shadowColor: COLORS.inkBlack, 
    shadowOffset: {width:0, height:8}, 
    shadowOpacity: 0.2, 
    shadowRadius: 15, 
    elevation: 8, 
    marginLeft: 15, 
    marginRight: 15 
  },
  cardImage: { flex: 1, width: '100%', borderRadius: 24 },
  cardOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, height: 180, borderRadius: 24 },
  cardTextContainer: { flex: 1, justifyContent: 'flex-end', padding: 25, backgroundColor: 'rgba(0,0,0,0.7)', borderBottomLeftRadius: 24, borderBottomRightRadius: 24 },
  cardTitle: { color: 'white', fontSize: 30, fontWeight: '700', textShadowColor: 'rgba(0,0,0,0.5)', textShadowOffset: {width:0, height:1}, textShadowRadius: 4 },
  cardAddress: { color: 'rgba(255,255,255,0.95)', fontSize: 17, fontWeight: '500', marginTop: 6 },
  cardPrice: { color: '#fff', fontSize: 24, fontWeight: '700' },
  cardUtility: { color: 'rgba(255,255,255,0.9)', fontSize: 17, fontWeight: '400' },
  topTabContainer: { flexDirection: 'row', backgroundColor: COLORS.inputBorder, padding: 4, marginHorizontal: 20, marginTop: 10, borderRadius: 12 },
  topTabBtn: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 10 },
  topTabBtnActive: { backgroundColor: COLORS.cardWhite, shadowColor: COLORS.inkBlack, shadowOpacity: 0.1, shadowRadius: 2 },
  topTabText: { fontWeight: '600', color: COLORS.mutedTeal, fontSize: 12 },
  topTabTextActive: { color: COLORS.darkTeal, fontWeight: 'bold' },
  requestCard: { padding: 20, backgroundColor: COLORS.cardWhite, marginBottom: 15, borderRadius: 16, shadowColor: COLORS.inkBlack, shadowOpacity:0.05, shadowRadius:5, elevation:2 },
  actions: { flexDirection: 'row', marginTop: 15, gap: 15 },
  btnReject: { flex: 1, backgroundColor: COLORS.cardWhite, borderWidth: 1, borderColor: COLORS.inputBorder, padding: 12, borderRadius: 12, alignItems: 'center' },
  btnAccept: { flex: 1, backgroundColor: COLORS.darkTeal, padding: 12, borderRadius: 12, alignItems: 'center' },
  housePicker: { width: '100%', height: 200, backgroundColor: COLORS.inputBorder, justifyContent: 'center', alignItems: 'center', marginBottom: 20, borderRadius: 16 },
  houseImg: { width: '100%', height: 200, borderRadius: 16 },
  avatarPicker: { width: 120, height: 120, borderRadius: 60, backgroundColor: COLORS.inputBorder, justifyContent: 'center', alignItems: 'center', marginBottom: 10, alignSelf:'center' },
  avatarImg: { width: 120, height: 120, borderRadius: 60 },
  infoBox: { width: '100%', backgroundColor: COLORS.cardWhite, padding: 15, borderBottomWidth: 1, borderColor: COLORS.inputBorder },
  infoLabel: { fontSize: 12, color: COLORS.mutedTeal, marginBottom: 2, textTransform:'uppercase' },
  infoValue: { fontSize: 16, fontWeight: '500', color: COLORS.inkBlack },
  miniPreview: { width: 100, height: 100, borderRadius: 10, backgroundColor: COLORS.inputBorder },
  addPhotoBtn: { width: 100, height: 100, borderRadius: 10, backgroundColor: COLORS.inputBorder, justifyContent: 'center', alignItems: 'center', borderWidth: 1, borderColor: COLORS.mutedTeal, borderStyle: 'dashed' },
  removePhotoBtn: { position: 'absolute', top: -5, right: -5, backgroundColor: COLORS.fadedCopper, width: 24, height: 24, borderRadius: 12, justifyContent: 'center', alignItems: 'center' },
  chatHeader: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 15, paddingVertical: 15, paddingTop:50, borderBottomWidth: 1, borderColor: COLORS.inputBorder, backgroundColor: COLORS.cardWhite },
  chatHeaderTitle: { fontSize: 18, fontWeight: 'bold', flex: 1, color: COLORS.inkBlack }, 
  chatListItem: { padding: 20, backgroundColor: COLORS.cardWhite, marginBottom: 1, borderBottomWidth:1, borderColor: COLORS.inputBorder },
  chatListTitle: { fontWeight: '600', fontSize: 16, color: COLORS.inkBlack },
  msgBubble: { padding: 12, borderRadius: 20, marginBottom: 8, maxWidth: '75%' },
  msgMine: { alignSelf: 'flex-end', backgroundColor: COLORS.mutedTeal, borderBottomRightRadius: 2 },
  msgTheirs: { alignSelf: 'flex-start', backgroundColor: COLORS.inputBorder, borderBottomLeftRadius: 2 },
  inputArea: { flexDirection: 'row', padding: 10, borderTopWidth: 1, borderColor: COLORS.inputBorder, alignItems: 'center', backgroundColor: COLORS.cardWhite },
  inputChat: { flex: 1, backgroundColor: COLORS.backgroundLight, padding: 12, borderRadius: 24, fontSize: 16, marginRight: 10, color: COLORS.inkBlack },
  sendBtn: { backgroundColor: COLORS.darkTeal, width: 44, height: 44, borderRadius: 22, justifyContent: 'center', alignItems: 'center' },
});

